allow-insecure-password: false

login-point:
  enable: false
  point:
    world: 'world'
    X: 0
    Y: 100
    Z: 0
  tp-back: true
  
skip-genuine-player: false

auto-login:
  enable: true
  allow-time(min): 120
  do-not-tp-to-loginpoint: true
  
allow-reset-password: false

prompts:
  title: true
  message:
    timer-delay(tick): 40
    
tone: true
player-kicks:
  wrongpassword: false
  server-reload: true

default-language: 'zh_cn'

date-format: 'yyyy-MM-dd hh:mm:ss'